var nb1= 2;
var nb2= 4;
var nb3= nb1+nb2;
console.log("Le résultat de :" +nb1+ "+" +nb2+  " est de" +nb3);
var nb1= 2;
var nb2= 4;
var nb3= nb1-nb2;
console.log("Le résultat de :" +nb1+ "-" +nb2+  " est de" +nb3);
var nb1= 2;
var nb2= 4;
var nb3= nb1*nb2;
console.log("Le résultat de :" +nb1+ "*" +nb2+ " est de" +nb3);
var nb1= 2;
var nb2= 4;
var nb3= nb1%nb2;
console.log("Le résultat de :" +nb1+ "%" +nb2+ " est de" +nb3);
var nb1= 2;
var nb2= 4;
var nb3= nb1/nb2;
console.log("Le résultat de :" +nb1+ "/" +nb2+  " est de" +nb3);
var nb1= 2;
var l2= "E";
var nb3= nb1 + l2;
console.log("Le résultat de :" +nb1+ "+" +l2+  " est de" +nb3);